- hosts: all
  name: Autoconverted job legacy-libec-pyeclib-unit from old job gate-libec-pyeclib-unit-ubuntu-xenial
  roles:
    - bindep

  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cd $WORKSPACE
          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            git://git.openstack.org \
            openstack/liberasurecode \
            openstack/pyeclib
          # build libec
          cd openstack/liberasurecode
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo bash -c "echo /usr/local/lib >> /etc/ld.so.conf"
          sudo ldconfig
          # test pyeclib
          cd $WORKSPACE/openstack/pyeclib
          tox -e py27
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
